apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-dataset
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      dataset.fluid.io/name: s3-dataset
      dataset.fluid.io/namespace: fluid-system
